/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

{{- if and (ne .Values.NAMESPACE "default") (ne .Values.NAMESPACE_DISABLED "yes") }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.NAMESPACE }}"
  namespace: "{{ .Values.NAMESPACE }}"
{{- end }}
